SECRET_KEY='sjfsjf;sfljsjfslfsfjs'

HOSTNAME='127.0.0.1'
PORT=3306
DATABASE='flask_forum'
USERNAME='root'
PASSWORD='666666'
DB_URI=f'mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}'
SQLALCHEMY_DATABASE_URI=DB_URI

MAIL_SERVER='smtp.qq.com'
MAIL_USE_SSL=True
MAIL_PORT=465
MAIL_USERNAME='2015426621@qq.com'
MAIL_PASSWORD='parjfeodwzucdfha'
MAIL_DEFAULT_SENDER='2015426621@qq.com'



