"""empty message

Revision ID: 26351f33f2d3
Revises: 657321d46a26
Create Date: 2025-07-31 15:13:44.337152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26351f33f2d3'
down_revision = '657321d46a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
