"""empty message

Revision ID: 5f5aa3905573
Revises: 6e0accf802ed
Create Date: 2025-08-04 22:20:57.111494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f5aa3905573'
down_revision = '6e0accf802ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=10), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
